version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  main:
    build:
      context: .
    volumes:
      - .:/var/www
    environment:
      VIRTUAL_HOST: laravel-lumen5.127.0.0.1.xip.io