version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  main:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      VIRTUAL_HOST: ${initSymfony5Url}
      PHPEXT_ENABLE_XDEBUG: "no"