name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Configuration
        run: |
          echo "::set-env name=TAG::elnebuloso/phing"
      - name: Version
        run: |
          export MAJOR=$(cat ./VERSION | cut -d. -f1)
          export MINOR=$(cat ./VERSION | cut -d. -f2)
          export PATCH=$(cat ./VERSION | cut -d. -f3)
          echo "::set-env name=MAJOR::$MAJOR"
          echo "::set-env name=MINOR::$MINOR"
          echo "::set-env name=PATCH::$PATCH"
      - name: Build
        run: |
          docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock --workdir /srv/phing --volume $(pwd)/main:/srv/phing composer install --no-suggest --no-ansi --no-interaction --no-dev --optimize-autoloader
          docker build --tag ${TAG} --pull --rm --no-cache --file Dockerfile .
      - name: Release
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ${TAG} ${TAG}:${MAJOR}.${MINOR}.${PATCH}
          docker tag ${TAG} ${TAG}:${MAJOR}.${MINOR}
          docker tag ${TAG} ${TAG}:${MAJOR}
          docker push ${TAG}:${MAJOR}.${MINOR}.${PATCH}
          docker push ${TAG}:${MAJOR}.${MINOR}
          docker push ${TAG}:${MAJOR}
          docker push ${TAG}
